"""
Django settings for brainweb project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

import dj_database_url

# Add Python user scripts to PATH (for nnUNetv2 executables) - Windows only
if os.name == 'nt':
    _appdata = os.environ.get("APPDATA", "")
    USER_SCRIPTS = os.path.join(_appdata, "Python", "Python314", "Scripts")
    _path = os.environ.get("PATH", "")
    if os.path.exists(USER_SCRIPTS) and USER_SCRIPTS not in _path:
        os.environ["PATH"] = USER_SCRIPTS + os.path.pathsep + _path




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Set nnU-Net environment variables
# Priority: environment variable > Railway volume > local data dir
_railway_vol = os.environ.get('RAILWAY_VOLUME_MOUNT_PATH', '')
_nnunet_base = Path(_railway_vol) / 'nnunet' if _railway_vol else BASE_DIR / 'data'

os.environ.setdefault("nnUNet_raw",          str(_nnunet_base / "nnUNet_raw"))
os.environ.setdefault("nnUNet_preprocessed", str(_nnunet_base / "nnUNet_preprocessed"))
os.environ.setdefault("nnUNet_results",      str(_nnunet_base / "nnUNet_results"))

# Ensure directories exist
for _env_var in ["nnUNet_raw", "nnUNet_preprocessed", "nnUNet_results"]:
    try:
        os.makedirs(os.environ[_env_var], exist_ok=True)
    except Exception as e:
        print(f"Warning: Could not create directory for {_env_var}: {e}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-*n@r%umaf@@m+ol%38@hrt(9*&s(n6@$x64ejg8d36q1orpb&^'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Railway va mahalliy uchun dynamik ALLOWED_HOSTS
ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    '*'
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tumor',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise: statik fayllarni production'da to'g'ri uzatadi
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'brainweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "tumor.context_processors.current_time",

            ],
        },
    },
]

WSGI_APPLICATION = 'brainweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL bo'lsa PostgreSQL, bo'lmasa SQLite
_db_url = os.environ.get('DATABASE_URL', '')
if _db_url:
    DATABASES = {'default': dj_database_url.config(default=_db_url, conn_max_age=600)}
else:
    # Render/Railway da yozish mumkin bo'lgan path ishlatamiz
    _sqlite_path = Path(os.environ.get('RENDER_SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')))
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _sqlite_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: faqat compress (Manifest ishlatilmaydi, crash larning oldini olish uchun)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media fayllar: Railway'da /data volume ga, mahallida BASE_DIR/media ga
MEDIA_URL = '/media/'
_railway_volume = os.environ.get('RAILWAY_VOLUME_MOUNT_PATH', '')
if _railway_volume:
    MEDIA_ROOT = Path(_railway_volume) / 'media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = "tumor:dashboard"
LOGOUT_REDIRECT_URL = "tumor:dashboard"

# Session ni DB siz cookie orqali saqlash (registratsiya talab qilmaydi)
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"



# Celery: Railway REDIS_URL o'zgaruvchisi bo'lsa Railway Redis, bo'lmasa local
_redis_url = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_BROKER_URL = _redis_url
CELERY_RESULT_BACKEND = _redis_url

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"


# CSRF: mahalliy + Railway + Render domenlarini qo'llab-quvvatlash
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://WIN-KNS5F51DB2S:8000",
    "https://*.up.railway.app",
    "https://*.railway.app",
    "https://*.onrender.com",
]

# Productionda HTTPS majburiy (Railway HTTPS ishlatadi)
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# settings.py (development)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "BrainWeb <no-reply@brainweb.local>"
SUPPORT_EMAIL = "support@brainweb.ai"
