# Generated by Django 5.2.8 on 2025-11-13 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, help_text='Clinic / Hospital ID (optional)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modality', models.CharField(choices=[('MRI', 'MRI'), ('CT', 'CT')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('nifti_file', models.FileField(blank=True, null=True, upload_to='nifti/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='tumor.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mask_nifti', models.FileField(upload_to='results/masks/')),
                ('bbox_png', models.ImageField(blank=True, null=True, upload_to='results/overlays/')),
                ('preview_png', models.ImageField(blank=True, null=True, upload_to='results/previews/')),
                ('tumor_volume_mm3', models.FloatField(blank=True, null=True)),
                ('tumor_max_diameter_mm', models.FloatField(blank=True, null=True)),
                ('bbox_x_min', models.IntegerField(blank=True, null=True)),
                ('bbox_y_min', models.IntegerField(blank=True, null=True)),
                ('bbox_z_min', models.IntegerField(blank=True, null=True)),
                ('bbox_x_max', models.IntegerField(blank=True, null=True)),
                ('bbox_y_max', models.IntegerField(blank=True, null=True)),
                ('bbox_z_max', models.IntegerField(blank=True, null=True)),
                ('predicted_class', models.CharField(blank=True, max_length=100)),
                ('predicted_confidence', models.FloatField(blank=True, null=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='tumor.study')),
            ],
        ),
    ]
