# Generated by Django 5.2.8 on 2025-12-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tumor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'permissions': [('upload_study', 'Can upload MRI/CT study'), ('review_study', 'Can medically review AI results')]},
        ),
    ]
