# Generated by Django 5.2.8 on 2025-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumor', '0002_alter_study_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='tumor_mesh_json',
            field=models.FileField(blank=True, null=True, upload_to='results/meshes/'),
        ),
    ]
