# Generated by Django 5.2.8 on 2025-12-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumor', '0003_airesult_tumor_mesh_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='bbox_diag_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesult',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesult',
            name='report_pdf_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='airesult',
            name='volumes_by_group',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
